Path clean up (/home/pi to ~), tweaks to github backup restore to make it easier
VoronDesign/Voron-Documentation pull request #398
Opened 2023-12-10 22:23 UTC by EricZimmerman

Path clean up (/home/pi to ~), tweaks to github backup restore to make it easier

2024-02-21 05:54 UTC, shiftingtech approved these changes

2024-02-21 05:56 UTC, shiftingtech commented
I think something blows up right at the end here
https://deploy-preview-398--dev-voron-documentation.netlify.app/community/howto/ericzimmerman/backupconfigtogithub#restoring-from-your-backup

2024-02-21 05:57 UTC, shiftingtech requested changes
The last section breaks down

2024-02-21 15:29 UTC, EricZimmerman commented
switched up to note and warning tags. does the thing auto stage a preview?

2024-02-22 03:53 UTC, shiftingtech approved these changes

2024-02-22 03:54 UTC, merged